version: "3.9"
services:
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movie_app_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
